[package]
name = "cita-forever"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
clap = "2"
logger = { git = "https://github.com/cryptape/cita-common.git", branch = "v0.21.1" }
util = { git = "https://github.com/cryptape/cita-common.git", branch = "v0.21.1" }

[build-dependencies]
util = { git = "https://github.com/cryptape/cita-common.git", branch = "v0.21.1" }
